# Generated by Django 4.0.4 on 2022-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='media/images/canva.png', upload_to='media/images'),
        ),
    ]
