# Generated by Django 4.0.4 on 2022-05-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image',
        ),
    ]
